In [1]:
import numpy as np

In [3]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

c.shape

(2, 3)

In [4]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [6]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

c.shape

(12288, 45)

In [30]:
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
print('a:', a)
print('a.T', a.T)
print('b', b)

c = a + b.T
print(c)
c.shape

('a:', array([[-0.48579361,  2.32995718, -0.18217383, -0.64131436],
       [ 0.71025909,  2.02402414,  0.26665856, -0.6787684 ],
       [ 0.41552407, -0.50859396, -1.11889453,  0.18098974]]))
('a.T', array([[-0.48579361,  0.71025909,  0.41552407],
       [ 2.32995718,  2.02402414, -0.50859396],
       [-0.18217383,  0.26665856, -1.11889453],
       [-0.64131436, -0.6787684 ,  0.18098974]]))
('b', array([[-1.02660727],
       [ 0.25485052],
       [-0.32746864],
       [-1.27698502]]))
[[-1.51240089  2.5848077  -0.50964246 -1.91829937]
 [-0.31634818  2.27887466 -0.06081008 -1.95575342]
 [-0.61108321 -0.25374344 -1.44636317 -1.09599527]]


(3, 4)

In [29]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(a)
print(b)

print(c)

[[-0.09845049 -0.77822013  2.5815289 ]
 [-1.58919705  1.23360347 -0.20781738]
 [ 0.80347796  1.66243604  0.2071841 ]]
[[-1.07107462]
 [-1.42640476]
 [ 0.11465006]]
[[ 0.10544782  0.83353182 -2.76501008]
 [ 2.26683822 -1.75961786  0.2964317 ]
 [ 0.0921188   0.19059839  0.02375367]]
